/**
 * Shared state for dashboard — обновляется из main loop
 */
export const dashboardState = {
  osc: {
    listening: false,
    port: 9001,
    portStatus: 'unknown',
    vrchatPortOpen: false,
    stale: false,
    lastPacketAt: 0,
    avatarChangedAt: 0,
  },
  oscQuery: {
    enabled: true,
    status: 'searching',
    httpHost: '',
    httpPort: 0,
    sendHost: '',
    sendPort: 0,
    hasBulk: false,
    waitingForBulk: false,
    lastBulkAt: 0,
    error: '',
    ready: false,
  },
  vrcConfig: {
    available: false,
    oscEnabled: null,
    selfInteractEnabled: null,
    everyoneInteractEnabled: null,
    error: '',
  },
  bhaptics: { connected: false, status: 'idle', error: '' },
  vrchat: { connected: false },
  avatar: { id: '', oscType: '' },
  lastUpdate: 0,
  contact: { value: 0, velocity: 0, duration: 0, eventType: 'idle', lastParam: '' },
  intensity: 0,
  lastHaptic: 0,
  stats: { messagesReceived: 0, hapticsSent: 0 },
  lastOscParams: {},
  allowZones: { chest: true, stomach: true, upperBack: true, lowerBack: true },
  allowWhile: { grounded: true, seated: true, inStation: true, afk: false },
  deviceInfo: { battery: null, devices: [], firmwareVersion: null },
  touchLog: [],
  lastMotorActivations: { indices: [], timestamp: 0 },
  lovense: {
    enabled: false,
    status: 'disabled',
    error: '',
    url: '',
    deviceCount: 0,
    deviceNames: [],
    lastIntensity: 0,
    lastSent: 0,
    ogbDeviceCount: 0,
    mode: 'ogb',
  },
};
